### PR TITLE
Make doCall protected so it can be accessed by classes that extend

### PR DESCRIPTION
**Pull request by wesleylancel**

### CODE REVIEW

**Comment by turanct** [comment]
why exactly would you want this method to be `protected`? there's no reason to extend a client class. if it's not feature complete with the api, you should create a pull request to make it so, not extend it inside your private code base. In fact, this class should be `final`?

**Comment by wesleylancel** [comment]
@turanct Why would you want to limit people from overriding certain parts of the library? What if I want to implement my own model with different fields than the one supplied by this library for example? I'm all for contributing back changes that benefit everyone, but that shouldn't impact extendability.

**Comment by turanct** [comment]
That's what adapters are for. No reason to extend a library to fit your own needs, you can just define your own objects and map those to the library's objects.

Practically all you need for this is a proper interface. Let's say you have an app that only cares about "person" with name and email, and your main store for them is Teamleader, you can do something like this:

```php
interface Store
{
    /**
     * @return Person
     */
    public function getPersonByEmail($email);

    /**
     * @param Person
     */
    public function store(Person $person);
}

final class Person
{
    // whatever you want here
}
```
your application then only needs to know about the `Person` object, that you created yourself. And you can have a Store with a Teamleader "backend" which populates your `Person` objects

```php
final class TeamleaderStore implements Store
{
    private $client;

    public function __construct(Teamleader $client)
    {
        $this->client = $client;
    }

    public function getPersonByEmail($email)
    {
        $TLContact = $this->client->crmGetContacts(1, 0, $email);

        $person = new Person($TLContact->getEmail(), $TLContact->getName());

        return $person;
    }

    public function store(Person $person)
    {
        // convert the other way 'round
    }
}
```

anyway, this keeps responsibilities separated and it keeps your application from having to update if something changes to the internals of the `Teamleader` class. If this library tomorrow renames the doCall method, you're basically f*cked if your application extends from it. Not if you have an adapter.

**Comment by wesleylancel** [comment]
Sure, yes, you can do all that. But I still don't see any reason to actively prevent anyone from extending the class.

**Comment by turanct** [comment]
The reason for doing that would be to make the extension points for the library really explicit. That class is not meant to be extended. If it would be, all methods (even protected methods) inside it are part of the "public" api of the library, and we would have to support that in the future, meaning, we can't change the inner workings of our library.

Anyway, i'm playing devil's advocate here, i don't think it's a good idea, but good luck in your endeavors. If you want to read more about this: http://verraes.net/2014/05/final-classes-in-php/

**Comment by carakas** [comment]
We discussed it internally and will go along with @turanct

**Comment by StijnVrolijk** [comment]
@carakas I'm eagerly awaiting your PR 🙂

**Pull request closed without merging**
